Algoritmo "Problema terreno"


Var

   base, altura, metQ, area, valor : real


Inicio

   escreval("Digite a largura do terreno: " )
   leia(base)
   escreval("Digite a comprimento do terreno ")
   leia(altura)
   escreval("DIgite o valor do metro quadrado ")
   leia(metQ)
   
   area <- base * altura
   valor <- area * metQ
   
   escreval("A area do terreno e = ", area:4:2)
   escreval("O valor do terre e = ", valor:4:2)




Fimalgoritmo